MyDataLab\Bundle\CoreBundle\Entity\Language:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        name:
            expose: true
        code:
            expose: true