imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        chromephp:
            type:   chromephp
            level:  info

#swiftmailer:
#    delivery_address: me@example.com

# Reference: https://github.com/willdurand/BazingaFakerBundle/blob/master/Resources/doc/index.md
bazinga_faker:
    orm: doctrine
    entities:
        MyDataLab\Bundle\ProductBundle\Entity\Product:
            number: 50
            custom_formatters:
                price:
                    method: randomElement
                    parameters:
                        - [1.5, 2.5, 3.6, 7, 44, 70, 79.33, 99.99, 120.3, 200.5, 200, 210, 300, 430, 502, 1003, 2000.5, 5001]
                priceOld:
                    method: randomElement
                    parameters:
                        - [1.5, 2.5, 3.6, 7, 44, 70, 79.33, 99.99, 120.3, 200.5, 200, 210, 300, 430, 502, 1003, 2000.5, 5001]
                priceTtcHt:
                    method: randomElement
                    parameters:
                        - [300, 500, 700]
                shipmentPrice:
                    method: randomElement
                    parameters:
                        - [10, 20, 30, 40]