# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
#                login_path: fos_user_secutiry_login
                check_path: fos_user_security_check
                default_target_path: my_data_lab_admin_dashboard
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous: true
    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%locale%/admin, role: ROLE_USER }
#        - { path: ^/%locale%/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%locale%/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/%locale%/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
