# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#
#   Translator search in app/Resources/translations and execute the .db files using translation.loader.db
    translation.loader.db:
        class: MyDataLab\Bundle\CoreBundle\TranslationsLoader
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: translation.loader, alias: db }
