<?php

namespace MyDataLab\Bundle\CrawlerBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingItemRepository extends \Doctrine\ORM\EntityRepository
{
}
