<?php

namespace MyDataLab\Bundle\WidgetBundle\Repository;

/**
 * DataCounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataCounterRepository extends \Doctrine\ORM\EntityRepository
{
}
