<?php

namespace MyDataLab\Bundle\WidgetBundle\Repository;

/**
 * UserWidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWidgetRepository extends \Doctrine\ORM\EntityRepository
{
}
