<?php

namespace MyDataLab\Bundle\GlossaryBundle\Repository;

/**
 * GlossaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlossaryRepository extends \Doctrine\ORM\EntityRepository
{
}
