<?php

namespace MyDataLab\Bundle\WhitePaperBundle\Repository;

/**
 * DocLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
