<?php

namespace MyDataLab\Bundle\PageRoutingBundle\Repository;

/**
 * PageRoutingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRoutingRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByLocale($locale = 'en')
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('pr')
                ->from($this->getEntityName(), 'pr')
                ->join('pr.language', 'l')
                ->where('l.code=:code')
                ->setParameter('code', $locale)
        ;
        return $qb->getQuery()->getResult();
    }

}
