<?php

namespace MyDataLab\Bundle\MarketSurveyBundle\Repository;

/**
 * MarketSurveryActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketSurveryActivityRepository extends \Doctrine\ORM\EntityRepository
{
}
