<?php

namespace MyDataLab\Bundle\MarketSurveyBundle\Repository;

/**
 * MarketSurveyMarketPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketSurveyMarketPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
