<?php

namespace MyDataLab\Bundle\MarketSurveyBundle\Repository;

/**
 * MarketSurveyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketSurveyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllMainCategories()
    {

    }
}
